### ISSUE TITLE
Update progress bar (feature 22) PR to new master

### ISSUE THREAD

**Issue by hanapc** [PaperHat/legal-checkup#101]
Acceptance Criteria:
1. Branch off techdebt/convert_to_lerna_and_add_server Branch
2. Copy your changes from _Closes 22 Create progressbar_ into the new branch
3. Open new PR pointing at Tech Debt Branch

**Comment by arist0cles** [comment]
Not sure if this PR is in a ready to merge state. If it is, let me know and I will clone the PR to point lerna
