### ISSUE TITLE
Add unique ID to clickable elements

### ISSUE THREAD

**Issue by hanapc** [PaperHat/legal-checkup#117]
Everything on the page that is clickable needs a ID that is unique so the testers 

**Acceptance Criteria:**
1. All elements in the Legal Checkup application that are clickable have a unique ID

**Comment by arist0cles** [comment]
- [ ]  Checkup
- [ ]  Layout
- [ ]  Link
- [ ]  Switchboard
- [ ]  Responsive
- [ ]  Results
- [ ]  Sitewrapper
