### ISSUE TITLE
Homepage!

### ISSUE THREAD

**Issue by the-hanalyst** [PaperHat/legal-checkup#125]
**Acceptance Criteria:**
1. The homepage of the checkup app informs the user about Community Law and the checkup:
    * Homepage (/) has content as per designs
    * The in-text link to *Wellington and Hutt Valley Community Law* links to "http://www.wclc.org.nz/"
2. Users can navigate to the checkup from the homepage
    * The "Start Check-up" button links to the check-up page (/checkup)
3. User can access Community Law Services information from the homepage
    * Services button displays on homepage
    * On selection of the services button, http://www.wclc.org.nz/our-services/ is loaded in a new tab
4. User can access information about Community Law from the homepage
    * About button displays on homepage
    * On selection of the services button, http://www.wclc.org.nz/about-us/ is loaded in a new tab

**Comment by ullibodnar** [comment]
I'm confused by this Acceptance Criteria. What does "User can access information about Community Law from the results page" mean?

**Comment by the-hanalyst** [comment]
Oh. COPY AND PASTE ERROR. Fixed now.
