### ISSUE TITLE
Fix font paths in app

### ISSUE THREAD

**Issue by the-hanalyst** [PaperHat/legal-checkup#128]
**Acceptance Criteria:**
1. Museo 500
2. Museo 900

The font IS here: `legal-checkup/packages/client/public/fonts/`
Except, we think that the URL that is being used in the the index file in the style folder needs to be updated (here: `legal-checkup/packages/client/src/styles/index.js`). It looks wrong?

The following needs to happen:
1. It needs to reference the path in the public folder
2. It only needs the `/fonts/`part added

**Comment by YWHo** [comment]
Found the free font at https://github.com/cssrocks/fonts/tree/master/Museo%20Sans%20Cyrillic
