### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by arist0cles** [PaperHat/legal-checkup#2]
UPDATED ACCEPTANCE CRITERIA:

The footer displays the following:
- The Copyright symbol, followed by a space, then: "2018 by Community Law Wellington and Hutt Valley" where "Community Law Wellington and Hutt Valley" is an external link to http://communitylaw.org.nz/
- Internal links to the following site pages:
    - Privacy Policy (/privacy)
    - Terms of Use (/terms)

Note: External links open in new tab.

Behaviour:
- When a link is activated, the footer triggers the load of the respective page.
- When the current page is one of the internal pages linked to by the footer (e.g., Terms of Use), then that link is replaced in the footer by placeholder text (i.e., it is no longer a link). 
- Footer displays correctly for screen-size.
- User can identify that it is a link

Designs:
- Desktop: https://zpl.io/blpWnl5
- Mobile: https://zpl.io/VKlqOQP

---------------------------------------
PREVIOUSLY:
Terms of Use
Privacy Policy

Manual Testing:
testCase1: Validate" Copyright 2018 by Community Law" 
Expected result: Copyright 2018 by Community Law
Actual result: © 2018 Community Law
Result: Fail
testCase2: Validate "Community Law" is an external link to http://communitylaw.org.nz/
Expected result : Opens the page "http://communitylaw.org.nz/"
Actual result: Opens the expected home page http://communitylaw.org.nz/
Result : Pass
TestCase3: Validate "internal link - Privacy Policy (/privacy)" page
Expected result: Navigates to Privacy Policy page
Actual result:  It navigates to Privacy-Policy page
Result: Pass
TestCase4: Validate "internal link - Terms of Use (/terms)" page
Expected result: Navigates to Terms of Use page
Actual result:  It navigates to Terms of Use  page
Result: Pass

TestCase5: Validate "When a link is activated, the footer triggers the load of the respective page."
Expected result: When a link is activated,   triggers the load of respective page.
Actual result:  It does triggers the load of the respective page.
Result: Pass

**Comment by hiremathpriya** [comment]
Manual testing done for the ACCEPTANCE CRITERIA above. 
Result: 1 Fail,
                3 Pass

**Comment by hanapc** [comment]
@latrellwhata  - to update the copyright to be realz and actual legal :)

**Comment by estak00** [comment]
Retested and Passed.Also branch  is ready to merge into master
