### ISSUE TITLE
Create ResultAccordion component

### ISSUE THREAD

**Issue by the-hanalyst** [PaperHat/legal-checkup#40]
Description:
This is the component that displays the results for a single topic. Use the UIKit Accordion component and pass it a Topic component and a Content component. Use Styled Components for Topic and Content (or Styled Component wrappers).

Acceptance Criteria:
 - [ ] Displays the Topic name
 - [ ] Is expanded by default
 - [ ] Displays expand/collapse toggle:
      - [ ] State 1: When the box is expanded:
                    -  an expand collapse toggle
                    -  The toggle is titled "Show Less"
                    -  On click, the box is collapsed (see state 2)
                    -  Results text displays for all "yes" answers for that topic
                    -  Where available, "what does the law say about this" link displays for each "yes" answer for that topic
                   - "What does the law say about this" link goes to the right place.
      - [ ] State 2: When the box is collapsed:
                   - an expand collapse toggle
                   * The toggle is titled "Show More"
                   * On click, the box is expanded (see state 1)
                   * No results text, or links to "what the law says about this" displays
 - [ ] Visually follows design:
      - [ ] Desktop version: https://zpl.io/VYkXxKE
      - [ ] Mobile version (see full set for all situations): https://zpl.io/bPvDeQk

**Comment by chasm** [comment]
Ask me if you have questions.

**Comment by YWHo** [comment]
Do we have Museo Sans 500 font? Otherwise, we probably can get it from:
https://www.dafontfree.net/find.php?q=museo+sans
(after clicking the link, scroll to bottom)

**Comment by hanapc** [comment]
Hi Brian,
I thought so, if it is, it should be in the styles folder.

**Comment by YWHo** [comment]
@chasm, what is the format of the JSON data to be passed into the props of this component?

**Comment by chasm** [comment]
Good question. Will think about it. With the switch to Gatsby, we will be moving from Redux/Redux Observable to GraphQL (and a different routing system, IIRC). Maybe its just the question object (everything you need should be in there).

**Comment by YWHo** [comment]
After looking at initialState/fixtures, and comparing the UI MockUp, I think the answer is topic object. The JSON format to be passed into the props should like below:

{  name: 'Money Troubles',
    questions : [
         { results: 'The fact that someone is chasing you for money',
          url:   'http://communitylaw.org.nz/community-law-manual/chapter-13-credit-and-debt/what-this-chapter-covers-chapter-13/'  },
         {  results: 'The problem you had recently had with a service you have brought',
             url:   'http://communitylaw.org.nz/community-law-manual/chapter-12-consumer-protection/what-this-chapter-covers-chapter-12/' }
    ] }


(The formatting is off, but I guess you could understand)
