### ISSUE TITLE
Enhance ProgressBar display

### ISSUE THREAD

**Issue by the-hanalyst** [PaperHat/legal-checkup#69]
Acceptance Criteria:
* Update display of the ProgressBar including:
     * Colours
     * Active question highlight
     * Arrow display

Should inherit the fonts from the global CSS update.

**Comment by hanapc** [comment]
Mobile: https://zpl.io/VOmmj8l
Tablet: https://zpl.io/2Goo60m
Desktop: https://zpl.io/boZZRQv
